// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class AchievementUnlock : UIViewController
	{
        public DailyChallenge controller;
        public AchievementManager.AchievementConfig unlockedAchievement;

		public AchievementUnlock (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            bottom.Layer.CornerRadius = 16;

            achievementPreview.Image = UIImage.FromFile("Image/Achievements/" + unlockedAchievement.ImageName);
            achievementName.Text = unlockedAchievement.AchievementName;

        }


        partial void debugButtom(NSObject sender)
        {
            //DismissViewController(true, null);
            this.PresentModalViewController(controller.controller, true);
        }
    }
}
