// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class ChallengeComplete : UIViewController
	{
        public UINavigationController ChallengeController;

        public UIImage image;

        public Challenges.Challenge challenge;

		public ChallengeComplete (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            System.Diagnostics.Debug.WriteLine("challenge load");

            ChallengeImage.Image = image;


            ChallengeName.Text = challenge.ChallengeName;
            TotalChallengeCompletetion.Text = Filewrite.totalChallenges().ToString();

            ChallengeImage.Layer.CornerRadius = 16;
            ChallengeButtom.Layer.CornerRadius = 16;

            complete.AdjustsFontSizeToFitWidth = ChallengeName.AdjustsFontSizeToFitWidth = complete.AdjustsFontSizeToFitWidth = true;

            var config = AchievementManager.nextAchievement();
            if (config != null)
            {
                AchievementManager.AchievementConfig realConfig = null;
                foreach (AchievementManager.AchievementConfig d in AchievementManager.achievements)
                {
                    if(d.AchievementID == config.AchievementID)
                    {
                        realConfig = d;
                    }
                }

                AchievementPreview.Image = UIImage.FromFile("Image/Achievements/" + config.ImageName);
                ToNextAchievement_Label.Text = (realConfig.ChallengeCount - config.ChallengeCount).ToString() + "/" + realConfig.ChallengeCount.ToString();
                System.Diagnostics.Debug.WriteLine(config.AchievementID);
            }
            else
            {
                stackView.RemoveArrangedSubview(toAchievement);
                toAchievement.RemoveFromSuperview();
                toAchievement.Dispose();
            }

        }

        partial void SubmitComplete(NSObject sender)
        {
            ChallengeController.PopViewController(false);
            ChallengeController.DismissModalViewController(true);
        }
    }
}
