// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class DailyTip : UINavigationItem
	{
		public DailyTip (IntPtr handle) : base (handle)
		{

		}
	}
}
