// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class Discover : UIViewController
	{

        public List<int> topics = new List<int>();

		public Discover (IntPtr handle) : base (handle)
		{

		}

        public async Task<string> hi()
        {
            string d = null;
            System.Diagnostics.Debug.WriteLine("hi");
            return d;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            foreach (UIView subView in rootStackView.ArrangedSubviews)
            {
                subView.RemoveFromSuperview();
            }

            rootStackView.Spacing = 16;
            rootStackView.LayoutMargins = new UIEdgeInsets(16, 0, 16, 0);
            rootStackView.LayoutMarginsRelativeArrangement = true;

            UICollectionView mainFeatureCollectionPage = new UICollectionView(new CGRect(10, 10, 10, 10), new DiscoverFlowLayout());
            mainFeatureCollectionPage.BackgroundColor = UIColor.Clear;
            rootStackView.AddArrangedSubview(mainFeatureCollectionPage);
            mainFeatureCollectionPage.HeightAnchor.ConstraintEqualTo(184).Active = true;
            mainFeatureCollectionPage.RegisterClassForCell(typeof(DiscoverCell), "hi");

            var featurePageSource = new DiscoverCollectionSource();
            featurePageSource.featureModule = new FeatureModule_September10();
            featurePageSource.featureModule.discoverPage = this;
            mainFeatureCollectionPage.Source = featurePageSource;
            var collectionViewLayout = new DiscoverCollectionFlowLayout(mainFeatureCollectionPage);
            mainFeatureCollectionPage.Delegate = collectionViewLayout;
            mainFeatureCollectionPage.DecelerationRate = UIScrollView.DecelerationRateFast;
            mainFeatureCollectionPage.ShowsHorizontalScrollIndicator = false;

            rootStackView.SetCustomSpacing(8, mainFeatureCollectionPage);


            for (int i = 0; i < 10; i++)
            {
                var discoverModule = DiscoveryCentral.GetModule(i, this);
                featurePageSource.featureModule.modules.Add(discoverModule);
                discoverModule.setController(this.NavigationController);
                discoverModule.asyncInitilize();

                var line = new UIView();
                line.BackgroundColor = UIColor.LightGray;
                rootStackView.AddArrangedSubview(line);
                line.HeightAnchor.ConstraintEqualTo(1).Active = true;
                rootStackView.SetCustomSpacing(8, line);

                rootStackView.AddConstraint(NSLayoutConstraint.Create(line, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Leading, 1.0f, 16f));
                rootStackView.AddConstraint(NSLayoutConstraint.Create(line, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Trailing, 1.0f, -16f));

                var TitleView = new UIView();

                UILabel header = new UILabel
                {
                    Text = discoverModule.Header,
                    Font = UIFont.BoldSystemFontOfSize(24),
                    ContentMode = UIViewContentMode.ScaleAspectFit,
                    AdjustsFontSizeToFitWidth = true,
                    TranslatesAutoresizingMaskIntoConstraints = false
                };

                header.SizeToFit();

                TitleView.HeightAnchor.ConstraintEqualTo(header.Frame.Height).Active = true;

                rootStackView.AddArrangedSubview(TitleView);

                rootStackView.AddConstraint(NSLayoutConstraint.Create(TitleView, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Leading, 1.0f, 16f));
                rootStackView.AddConstraint(NSLayoutConstraint.Create(TitleView, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Trailing, 1.0f, -16f));

                TitleView.AddSubview(header);

                UIView backView = TitleView;
                var backViewState = NSLayoutAttribute.Trailing;
                int backViewDistance = -16;

                if (discoverModule.expansionButtonVisibility())
                {
                    UIButton expansionButton = new UIButton
                    {
                        ContentMode = UIViewContentMode.ScaleAspectFit,
                        TranslatesAutoresizingMaskIntoConstraints = false,
                        Font = UIFont.SystemFontOfSize(16),
                    };

                    discoverModule.expandButton = expansionButton;

                    expansionButton.SetTitle(NSBundle.MainBundle.GetLocalizedString("See All"), UIControlState.Normal);
                    expansionButton.SetTitleColor(expansionButton.TintColor, UIControlState.Normal);

                    expansionButton.SizeToFit();

                    expansionButton.TouchUpInside += (object sender, System.EventArgs e) => {
                        expand(discoverModule);
                    };

                    backView = expansionButton;
                    backViewState = NSLayoutAttribute.Leading;

                    expansionButton.WidthAnchor.ConstraintEqualTo(expansionButton.Frame.Width).Active = true;

                    TitleView.AddSubview(expansionButton);

                    TitleView.AddConstraint(NSLayoutConstraint.Create(expansionButton, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, TitleView, NSLayoutAttribute.Trailing, 1.0f, 0));
                    TitleView.AddConstraint(NSLayoutConstraint.Create(expansionButton, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, TitleView, NSLayoutAttribute.Bottom, 1.0f, 0));
                    backViewDistance = -8;
                }

                TitleView.AddConstraint(NSLayoutConstraint.Create(header, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, TitleView, NSLayoutAttribute.Leading, 1.0f, 0));
                TitleView.AddConstraint(NSLayoutConstraint.Create(header, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, backView, backViewState, 1.0f, backViewDistance));

                rootStackView.SetCustomSpacing(6, TitleView);

                if(discoverModule.secondaryHeaderVisibility())
                {
                    rootStackView.SetCustomSpacing(3, header);

                    UILabel secondaryHeader = new UILabel
                    {
                        Text = discoverModule.secondaryHeader,
                        Font = UIFont.SystemFontOfSize(18),
                        ContentMode = UIViewContentMode.ScaleAspectFit,
                        AdjustsFontSizeToFitWidth = true,
                        TextColor = UIColor.LightGray
                    };
                    rootStackView.AddArrangedSubview(secondaryHeader);

                    rootStackView.AddConstraint(NSLayoutConstraint.Create(secondaryHeader, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Leading, 1.0f, 16f));
                    rootStackView.AddConstraint(NSLayoutConstraint.Create(secondaryHeader, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, rootStackView, NSLayoutAttribute.Trailing, 1.0f, -16f));

                    rootStackView.SetCustomSpacing(6, secondaryHeader);
                }

                UICollectionView smallCollection = new UICollectionView(new CGRect(10, 10, 10, 10), new DiscoverFlowLayout());
                smallCollection.BackgroundColor = UIColor.Clear;
                rootStackView.AddArrangedSubview(smallCollection);
                smallCollection.HeightAnchor.ConstraintEqualTo(128).Active = true;
                smallCollection.RegisterClassForCell(typeof(SmallDiscoverCell), "hi");
                smallCollection.Source = new SmalleDiscoverCollectionSource(discoverModule);
                var smallCollectionView = new SmallDiscoverFlowLayout(smallCollection, discoverModule);
                smallCollection.Delegate = smallCollectionView;
                smallCollection.DecelerationRate = UIScrollView.DecelerationRateFast;
                smallCollection.ShowsHorizontalScrollIndicator = false;

                rootStackView.SetCustomSpacing(8, smallCollection);

                discoverModule.uicollectionView = smallCollection;
                discoverModule.collectionViewAssigned();
            }
            /*
            CollectionViewTest.SetCollectionViewLayout(new DiscoverFlowLayout(), false);
            CollectionViewTest.RegisterClassForCell(typeof(DiscoverCell), "hi");
            CollectionViewTest.Source = new DiscoverCollectionSource();
            var collectionViewLayout = new DiscoverCollectionFlowLayout(CollectionViewTest);
            CollectionViewTest.Delegate = collectionViewLayout;
            CollectionViewTest.DecelerationRate = UIScrollView.DecelerationRateFast;

            smallCollectionView.SetCollectionViewLayout(new DiscoverFlowLayout(), false);
            smallCollectionView.RegisterClassForCell(typeof(SmallDiscoverCell), "hi");
            smallCollectionView.Source = new SmalleDiscoverCollectionSource();
            var smallCollectionViewLayout = new SmallDiscoverFlowLayout(smallCollectionView);
            smallCollectionView.Delegate = smallCollectionViewLayout;
            smallCollectionView.DecelerationRate = UIScrollView.DecelerationRateFast;*/

        }

        public void expand(DiscoverModule module)
        {
            DiscoverDetail detailPage = this.Storyboard.InstantiateViewController("DiscoverDetail") as DiscoverDetail;
            detailPage.module = module;
            this.NavigationController.PushViewController(detailPage, true);
        }
    }
}
