// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class DiscoverDetail : UIViewController
	{
        public DiscoverModule module;

		public DiscoverDetail (IntPtr handle) : base (handle)
		{

        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            /*
            foreach (UIView item in NavigationController.NavigationBar.Subviews)
            {
                foreach(UIView subview in item.Subviews)
                {
                    if (subview is UILabel)
                    {
                        System.Diagnostics.Debug.WriteLine("true" + subview.AccessibilityLabel + ((UILabel)subview).Text);
                    }
                }
            }*/

            header.Title = module.Header;

            foreach (UIView d in stackView.ArrangedSubviews)
            {
                d.RemoveFromSuperview();
            }

            stackView.LayoutMargins = new UIEdgeInsets(16, 16, 16, 16);
            stackView.LayoutMarginsRelativeArrangement = true;

            stackView.Spacing = 8;

            for (int i = 0; i < module.getRowCount(); i++)
            {
                SmallDiscoverCell challenge = new SmallDiscoverCell(new CGRect(0, 0, UIScreen.MainScreen.Bounds.Width, 111));

                challenge.ContentMode = UIViewContentMode.ScaleAspectFit;
                //challenge.BackgroundColor = UIColor.Red;
                stackView.AddArrangedSubview(challenge);

                challenge.HeightAnchor.ConstraintEqualTo(111).Active = true;

                challenge.Initialize(module, NSIndexPath.FromRowSection(i, 0));

                var recognizer = new UITapGestureRecognizer(onModuleTap);
                challenge.AddGestureRecognizer(recognizer);
                recognizer.View.Tag = i;
            }
        }

        void onModuleTap(UITapGestureRecognizer tap)
        {
            module.itemSelected(NSIndexPath.FromRowSection(tap.View.Tag, 0));
        }
    }
}
