// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using Footprint.Base.lproj;
using System.Reflection;
using System.Linq;
using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class SurveyMenu : UIViewController
	{
        public Dictionary<string, bool> surveys = new Dictionary<string, bool>();

		public SurveyMenu (IntPtr handle) : base (handle)
		{

		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var assembly = Assembly.GetExecutingAssembly();

            string resourceName = assembly.GetManifestResourceNames().Single(str => str.EndsWith("SurveyCatalog.xml"));

            Stream stream = assembly.GetManifestResourceStream(resourceName);

            XmlReader xtr = XmlReader.Create(stream);

            while (xtr.Read())
            {
                if (xtr.NodeType == XmlNodeType.Element && xtr.Name == "survey")
                {
                    surveys.Add(xtr.GetAttribute("name"), xtr.GetAttribute("localization").Contains(NSBundle.MainBundle.PreferredLocalizations[0]));
                }
            }

            uiCell.Source = new SurveyCatalogTableSource(surveys, this);



        }

        public void OpenSurvey(string key)
        {
            string fileName = key;
             if(surveys[key])
            {
                key += "_" + NSBundle.MainBundle.PreferredLocalizations[0];
            }

            key += ".xml";

            SurveyView surveyView = this.Storyboard.InstantiateViewController("SurveyView") as SurveyView;
            var surveyController = new UINavigationController(surveyView);
            var surveyClass = new SurveyClass(key);
            surveyClass.Start(surveyView);
            surveyView.menu = this;
            this.NavigationController.PresentViewController(surveyController, true, null);
        }
    }
}
