// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using Foundation;
using System.Linq;
using System.Collections.Generic;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class SurveyView : UIViewController
	{
		public SurveyView (IntPtr handle) : base (handle)
		{

		}

        public SurveyClass surveyClass;
        public SurveyClass.SurveyModule module;
        public SurveyMenu menu;

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            System.Diagnostics.Debug.WriteLine("willwork");
            this.NavigationController.SetNavigationBarHidden(true, false);
            nextButton.Layer.CornerRadius = 16;
            SurveyPicker surveyPicker = new SurveyPicker(module.responses, surveyClass);
            picker.Model = surveyPicker;
            question.Text = module.questions;
            surveyLabel.Text = surveyClass.name;
        }

        public void DismissAll()
        {
            menu.NavigationController.DismissViewController(true, null);
        }

        partial void next(NSObject sender)
        {

            SurveyView surveyView = this.Storyboard.InstantiateViewController("SurveyView") as SurveyView;
            surveyView.menu = menu;
            surveyClass.CompleteSurvey(module.responses.ElementAt((int)picker.SelectedRowInComponent(0)).Value, surveyView, module, module.responses.ElementAt((int)picker.SelectedRowInComponent(0)).Key);
            //this.NavigationController.PushViewController(surveyView, true);
        }

        public void DoubleChoice()
        {
            UIButton button = new UIButton();
            button.BackgroundColor = UIColor.Blue;
        }
    }
}
