// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class UsernameChange : UIViewController
	{
        public Me me;

		public UsernameChange (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            usernameField.Text = Filewrite.LoadUsername();
        }

        partial void complete(NSObject sender)
        {
            if(usernameField.Text != "")
            {
                me.SubmitUsernameChange(usernameField.Text);
            }
            DismissModalViewController(true);
        }
    }
}
