 // This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint
{
	public partial class About : UIViewController
	{
		public About (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            AboutText.Text = NSBundle.MainBundle.GetLocalizedString("Developer About");
            CopyrightText.Text = NSBundle.MainBundle.GetLocalizedString("All rights reserved © 2019 Jingcheng Yang");
        }

        //public override bool HidesBottomBarWhenPushed { get => base.HidesBottomBarWhenPushed; set => base.HidesBottomBarWhenPushed = true; }
    }
}
