// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint
{
	public class DailyHub : UIViewController
	{
		public DailyHub (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var stackView = new UIStackView
            {
                Axis = UILayoutConstraintAxis.Vertical,
                // make the inner views to fill the whole available width
                Alignment = UIStackViewAlignment.Fill, 
                Distribution = UIStackViewDistribution.EqualSpacing,
                // margin between views
                Spacing = 4, 
                // apply padding between the parent view (the scroll) 
                // and the stack
                LayoutMargins = new UIEdgeInsets(4, 4, 4, 4),
                // this will make padding actually work
                LayoutMarginsRelativeArrangement = true 
            };

            var scroll = new UIScrollView();
            Add(scroll);

            scroll.AddSubview(stackView);

            for (var i = 0; i < 20; i++)
                stackView.AddArrangedSubview(GetRandomView());

            
            scroll.EnableAutoLayout();

            scroll.FullSizeOf(View); 
            stackView.FullSizeOf(scroll);

            stackView.WidthAnchor.ConstraintEqualTo(scroll.WidthAnchor).Active = true;
        }

        private static UIView GetRandomView()
        {
            var view = new UIView();
            view.BackgroundColor = UIColor.Blue;
            view.Layer.CornerRadius = 8;

            var randomHeight = 100;
            view.HeightAnchor.ConstraintEqualTo(randomHeight).Active = true;
            return view;
        }
    }
}
