// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Footprint
{
	public partial class HubDaily : UIViewController
	{
        int tipImage;
        TipLibrary.Tip tip;
        List<Challenges.Challenge> activeChallenges = new List<Challenges.Challenge>();


        UIView noChallenges;

        public Dictionary<string, UIView> challengePads = new Dictionary<string, UIView>();
        public Dictionary<string, UILabel> challengeSecondary_Label = new Dictionary<string, UILabel>();

        
        public HubDaily (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            if (Filewrite.LoadChallenge() == null)
            {
                return;
            }
            else if(noChallenges != null && Filewrite.LoadChallenge().Count > 0)
            {
                noChallenges.RemoveFromSuperview();
            }

            int index = challengePads.Count + 3;


             
            foreach(string challengeID in Filewrite.LoadChallenge())
            {
                if(!challengePads.ContainsKey(challengeID))
                {
                    //add
                     //copy from the main convesion, change the final insertation

                    var chosenChallenge = Challenges.LoadChallenge(challengeID);

                    UIView challenge = new UIView();
                    challenge.ContentMode = UIViewContentMode.ScaleAspectFit;

                    //insertation change here
                    stackView.InsertArrangedSubview(challenge, (nuint)index);
                    index += 1;

                    challenge.BackgroundColor = colorManager.color(chosenChallenge.ConditionValue);

                    challenge.Layer.CornerRadius = 16;
                    challenge.HeightAnchor.ConstraintEqualTo(111).Active = true;

                    challenge.UserInteractionEnabled = true;
                    challengeTapRecognizer tap_Gesture = new challengeTapRecognizer(challenge, this, chosenChallenge);
                    tap_Gesture.ChallengeID = chosenChallenge.ChallengeID;
                    tap_Gesture.view = challenge;

                    tap_Gesture.NumberOfTapsRequired = 1;
                    challenge.AddGestureRecognizer(tap_Gesture);
                    tap_Gesture.View.Tag = activeChallenges.IndexOf(chosenChallenge);

                    UIImageView icon = new UIImageView();
                    icon.TranslatesAutoresizingMaskIntoConstraints = false;
                    challenge.AddSubview(icon);

                    icon.Image = imageManager.iconOfIndex(chosenChallenge.ConditionValue);

                    challengePads.Add(chosenChallenge.ChallengeID, challenge);

                    challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 78.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Width, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 78.0f));

                    challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Leading, 1.0f, 16.0f));

                   

                    if (chosenChallenge.challengeType == Challenges.Challenge.ChallengeType.OneTime)
                    {
                        UILabel label = new UILabel
                        {
                            Text = chosenChallenge.ChallengeName,
                            Font = UIFont.BoldSystemFontOfSize(39),
                            TextColor = UIColor.White,
                            AdjustsFontSizeToFitWidth = true
                        };
                        label.TranslatesAutoresizingMaskIntoConstraints = false;
                        challenge.AddSubview(label);

                        //challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 77.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));
                    }
                    else
                    {
                        UILabel label = new UILabel
                        {
                            Text = chosenChallenge.ChallengeName,
                            Font = UIFont.BoldSystemFontOfSize(39),
                            TextColor = UIColor.White,
                            AdjustsFontSizeToFitWidth = true
                        };
                        label.TranslatesAutoresizingMaskIntoConstraints = false;
                        challenge.AddSubview(label);

                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 45.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));

                        UILabel secondaryLabel = new UILabel
                        {
                            Text = "Secondary",
                            Font = UIFont.SystemFontOfSize(17),
                            TextColor = UIColor.White,
                            AdjustsFontSizeToFitWidth = true
                        };
                        secondaryLabel.TranslatesAutoresizingMaskIntoConstraints = false;
                        challenge.AddSubview(secondaryLabel);

                        challengeSecondary_Label.Add(chosenChallenge.ChallengeID, secondaryLabel);

                        challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -6.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Top, NSLayoutRelation.Equal, label, NSLayoutAttribute.Bottom, 1.0f, 6.0f));
                        challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));

                        if (!Filewrite.NotDone(chosenChallenge.ChallengeID))
                        {
                            secondaryLabel.Text = NSBundle.MainBundle.GetLocalizedString("COMPLETE FOR TODAY");
                        }
                        else
                        {
                            if (chosenChallenge.RequiredDays < 3)
                            {
                                secondaryLabel.Text = chosenChallenge.RequiredDays.ToString() + NSBundle.MainBundle.GetLocalizedString("DAYS TO GO !");
                            }
                            else
                            {
                                secondaryLabel.Text = NSBundle.MainBundle.GetLocalizedString("NOT DONE");
                            }
                        }
                    }

                    AddShadow(challenge);
                }
            }
             /*
            stackView.Axis = UILayoutConstraintAxis.Vertical;

            foreach (UIView view in stackView.Subviews)
            {
                view.Hidden = true;
                view.Alpha = 0;

                UIView.Animate(duration: 0.3f, delay: 0, options: UIViewAnimationOptions.TransitionCurlDown, animation: () =>
                {
                    view.Hidden = false;
                    view.Alpha = 1;
                },

                completion: () =>
                {
                    view.Hidden = false;
                    view.Alpha = 1;
                });
            }*/

        }

        public void addPad()
        {
            noChallenges = new UIView();
            noChallenges.ContentMode = UIViewContentMode.ScaleAspectFit;
            stackView.AddArrangedSubview(noChallenges);
            noChallenges.BackgroundColor = UIColor.QuaternarySystemFillColor;
            noChallenges.Layer.CornerRadius = 16;
            noChallenges.HeightAnchor.ConstraintEqualTo(64).Active = true;
            AddShadow(noChallenges);

            UILabel label = new UILabel
            {
                Text = NSBundle.MainBundle.GetLocalizedString("No Challenges Added"),
                Font = UIFont.SystemFontOfSize(16),
                TextColor = UIColor.LabelColor,
                AdjustsFontSizeToFitWidth = true,
                BaselineAdjustment = UIBaselineAdjustment.AlignCenters,
                TextAlignment = UITextAlignment.Center
            };
            label.TranslatesAutoresizingMaskIntoConstraints = false;
            noChallenges.AddSubview(label);

            //challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 77.0f));
            noChallenges.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, noChallenges, NSLayoutAttribute.Leading, 1.0f, 8.0f));
            noChallenges.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, noChallenges, NSLayoutAttribute.Trailing, 1.0f, -8.0f));
            noChallenges.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Top, NSLayoutRelation.Equal, noChallenges, NSLayoutAttribute.Top, 1.0f, 8.0f));
            noChallenges.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, noChallenges, NSLayoutAttribute.Bottom, 1.0f, -8.0f));
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            System.Diagnostics.Debug.WriteLine("scroll type = " + scroll.ContentInsetAdjustmentBehavior);
            //scroll.ContentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentBehavior.Always;

            //initialization
            var random = new System.Random();
            tipImage = random.Next(0, 6);
            tip = TipLibrary.tips[random.Next(0, TipLibrary.tips.Count - 1)];

            //ui

            foreach (UIView d in stackView.ArrangedSubviews)
            {
                d.RemoveFromSuperview();
            }

            stackView.LayoutMargins = new UIEdgeInsets(16, 16, 16, 16);
            stackView.LayoutMarginsRelativeArrangement = true;

            stackView.Spacing = 8;

            UILabel tipLabel = new UILabel
            {
                Text = NSBundle.MainBundle.GetLocalizedString("Daily Tip"),
                Font = UIFont.BoldSystemFontOfSize(24),
                ContentMode = UIViewContentMode.ScaleAspectFit,
            };

            stackView.AddArrangedSubview(tipLabel);


            UIView dailyTip = new UIView();
            dailyTip.ContentMode = UIViewContentMode.ScaleAspectFit;
            stackView.AddArrangedSubview(dailyTip);
            dailyTip.HeightAnchor.ConstraintEqualTo(230).Active = true;

            UIImageView image = new UIImageView();
            image.Layer.CornerRadius = 16;
            dailyTip.AddSubview(image);
            image.TranslatesAutoresizingMaskIntoConstraints = false;
            dailyTip.AddConstraint(NSLayoutConstraint.Create(image, NSLayoutAttribute.Height, NSLayoutRelation.Equal, dailyTip, NSLayoutAttribute.Height, 1.0f, 0.0f));
            dailyTip.AddConstraint(NSLayoutConstraint.Create(image, NSLayoutAttribute.Width, NSLayoutRelation.Equal, dailyTip, NSLayoutAttribute.Width, 1.0f, 0.0f));
            image.UserInteractionEnabled = true;
            UITapGestureRecognizer tapGesture = new UITapGestureRecognizer(Tap);
            tapGesture.NumberOfTapsRequired = 1;
            image.AddGestureRecognizer(tapGesture);
            tapGesture.View.Tag = -1;

            AddShadow(dailyTip);

            UIImageView dailyTip_Icon = new UIImageView();
            dailyTip_Icon.TranslatesAutoresizingMaskIntoConstraints = false;
            image.AddSubview(dailyTip_Icon);

            image.AddConstraint(NSLayoutConstraint.Create(dailyTip_Icon, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 84.0f));
            image.AddConstraint(NSLayoutConstraint.Create(dailyTip_Icon, NSLayoutAttribute.Width, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 84.0f));
            image.AddConstraint(NSLayoutConstraint.Create(dailyTip_Icon, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, image, NSLayoutAttribute.Leading, 1.0f, 16.0f));
            image.AddConstraint(NSLayoutConstraint.Create(dailyTip_Icon, NSLayoutAttribute.Top, NSLayoutRelation.Equal, image, NSLayoutAttribute.Top, 1.0f, 16.0f));

            UILabel tipName = new UILabel
            {
                Text = "Test",
                Font = UIFont.SystemFontOfSize(44, UIFontWeight.Bold),
                TextColor = UIColor.White,
                AdjustsFontSizeToFitWidth = true
            };
            tipName.TranslatesAutoresizingMaskIntoConstraints = false;
            image.AddSubview(tipName);

            image.AddConstraint(NSLayoutConstraint.Create(tipName, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 64.0f));
            image.AddConstraint(NSLayoutConstraint.Create(tipName, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, image, NSLayoutAttribute.Leading, 1.0f, 11.0f));
            image.AddConstraint(NSLayoutConstraint.Create(tipName, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, image, NSLayoutAttribute.Trailing, 1.0f, -11.0f));
            image.AddConstraint(NSLayoutConstraint.Create(tipName, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, image, NSLayoutAttribute.Bottom, 1.0f, -16.0f));

            UILabel challengeLabel = new UILabel
            {
                Text = NSBundle.MainBundle.GetLocalizedString("Challenges"),
                Font = UIFont.BoldSystemFontOfSize(24),
                ContentMode = UIViewContentMode.ScaleAspectFit,
            };

            //finalize tip

            image.Image = UIImage.FromFile("Image/ChallengeTopic/" + tip.ConditionIndex.ToString() + "/" + tipImage.ToString() + ".jpg");
            image.Layer.CornerRadius = 16;
            image.ClipsToBounds = true;
            image.ContentMode = UIViewContentMode.ScaleAspectFill;
            tipName.Text = tip.TipName;
            dailyTip_Icon.Image = imageManager.iconOfIndex(tip.ConditionIndex);


            stackView.AddArrangedSubview(challengeLabel);
            stackView.SetCustomSpacing(24, dailyTip);

            //complete with tips

            var activeChallengeStrings = Filewrite.LoadChallenge();

            if (activeChallengeStrings != null && activeChallengeStrings.Count > 0)
            {
                foreach (string name in activeChallengeStrings)
                {
                     activeChallenges.Add(Challenges.LoadChallenge(name));
                }
            }
            else
            {
                addPad();


                return;
            }

            //initialized

            foreach(Challenges.Challenge chosenChallenge in activeChallenges)
            {

                UIView challenge = new UIView();
                challenge.ContentMode = UIViewContentMode.ScaleAspectFit;
                stackView.AddArrangedSubview(challenge);

                challenge.BackgroundColor = colorManager.color(chosenChallenge.ConditionValue);
                challenge.Layer.CornerRadius = 16;
                challenge.HeightAnchor.ConstraintEqualTo(111).Active = true;

                challenge.UserInteractionEnabled = true;
                challengeTapRecognizer tap_Gesture = new challengeTapRecognizer(challenge, this, chosenChallenge);
                tap_Gesture.ChallengeID = chosenChallenge.ChallengeID;

                tap_Gesture.view = challenge;
                
                tap_Gesture.NumberOfTapsRequired = 1;
                challenge.AddGestureRecognizer(tap_Gesture);
                tap_Gesture.View.Tag = activeChallenges.IndexOf(chosenChallenge);

                UIImageView icon = new UIImageView();
                icon.TranslatesAutoresizingMaskIntoConstraints = false;
                challenge.AddSubview(icon);

                icon.Image = imageManager.iconOfIndex(chosenChallenge.ConditionValue);

                challengePads.Add(chosenChallenge.ChallengeID, challenge);

                challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 78.0f));
                challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Width, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 78.0f));

                challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));
                challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));
                challenge.AddConstraint(NSLayoutConstraint.Create(icon, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Leading, 1.0f, 16.0f));

                //challenge.Layer.AddSublayer(colorManager.gradientColor(challenge));

                AddShadow(challenge);

                if (chosenChallenge.challengeType == Challenges.Challenge.ChallengeType.OneTime)
                {
                    UILabel label = new UILabel
                    {
                        Text = chosenChallenge.ChallengeName,
                        Font = UIFont.BoldSystemFontOfSize(39),
                        TextColor = UIColor.White,
                        AdjustsFontSizeToFitWidth = true
                    };
                    label.TranslatesAutoresizingMaskIntoConstraints = false;
                    challenge.AddSubview(label);

                    //challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 77.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));
                }
                else
                {
                    UILabel label = new UILabel
                    {
                        Text = chosenChallenge.ChallengeName,
                        Font = UIFont.BoldSystemFontOfSize(39),
                        TextColor = UIColor.White,
                        AdjustsFontSizeToFitWidth = true
                    };
                    label.TranslatesAutoresizingMaskIntoConstraints = false;
                    challenge.AddSubview(label);

                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Height, NSLayoutRelation.Equal, null, NSLayoutAttribute.NoAttribute, 1.0f, 45.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(label, NSLayoutAttribute.Top, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Top, 1.0f, 16.0f));

                    UILabel secondaryLabel = new UILabel
                    {
                        Text = "Secondary",
                        Font = UIFont.SystemFontOfSize(17),
                        TextColor = UIColor.White,
                        AdjustsFontSizeToFitWidth = true
                    };
                    secondaryLabel.TranslatesAutoresizingMaskIntoConstraints = false;
                    challenge.AddSubview(secondaryLabel);

                    challengeSecondary_Label.Add(chosenChallenge.ChallengeID, secondaryLabel);

                    challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Leading, NSLayoutRelation.Equal, icon, NSLayoutAttribute.Trailing, 1.0f, 16.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Trailing, 1.0f, -6.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Top, NSLayoutRelation.Equal, label, NSLayoutAttribute.Bottom, 1.0f, 6.0f));
                    challenge.AddConstraint(NSLayoutConstraint.Create(secondaryLabel, NSLayoutAttribute.Bottom, NSLayoutRelation.Equal, challenge, NSLayoutAttribute.Bottom, 1.0f, -16.0f));

                    if (!Filewrite.NotDone(chosenChallenge.ChallengeID))
                    {
                        secondaryLabel.Text = NSBundle.MainBundle.GetLocalizedString("COMPLETE FOR TODAY");
                    }
                    else
                    {
                        if (chosenChallenge.RequiredDays < 3)
                        {
                            secondaryLabel.Text = chosenChallenge.RequiredDays.ToString() + NSBundle.MainBundle.GetLocalizedString("DAYS TO GO !");
                        }
                        else
                        {
                            secondaryLabel.Text = NSBundle.MainBundle.GetLocalizedString("NOT DONE");
                        }
                    }
                }
                 /*
                end = new UIView();
                end.ContentMode = UIViewContentMode.ScaleAspectFit;
                stackView.AddArrangedSubview(end);
                end.HeightAnchor.ConstraintEqualTo(0).Active = true;*/

            }

             List<string> discontinuedChallenges = new List<string>();

            foreach(Challenges.Challenge challenge in activeChallenges)
            {
                if(challenge.challengeType == Challenges.Challenge.ChallengeType.ForceDaily)
                {
                     if(Filewrite.StreakBroken(challenge.ChallengeID))
                    {
                        System.Diagnostics.Debug.WriteLine("Streak broken" + challenge.ChallengeID);
                        discontinuedChallenges.Add(challenge.ChallengeID);
                    }
                }
            }
            if(discontinuedChallenges.Count > 0)
            {
                List<string> discontinuedChallengeName = new List<string>();
                foreach(string d in discontinuedChallenges)
                {
                    discontinuedChallengeName.Add(Challenges.getChallengeByID(d).ChallengeName);
                }

                string challengesText = string.Join(", ", discontinuedChallengeName.ToArray());
                string alertSentence = NSBundle.MainBundle.GetLocalizedString("Your following force-daily challenges have been discontinued : ") + challengesText;
                if(discontinuedChallenges.Count == 1)
                {
                    alertSentence = NSBundle.MainBundle.GetLocalizedString("Your force-daily challenge ") + "'" + challengesText + "' " + NSBundle.MainBundle.GetLocalizedString("has been discontinued");
                }


                var okAlertController = UIAlertController.Create(NSBundle.MainBundle.GetLocalizedString("Challenge Discontinued"), alertSentence, UIAlertControllerStyle.Alert);

                //Add Action
                okAlertController.AddAction(UIAlertAction.Create(NSBundle.MainBundle.GetLocalizedString("Dismiss"), UIAlertActionStyle.Default, (action) => removeDiscontinuedChallenges(discontinuedChallenges)));

                // Present Alert
                PresentViewController(okAlertController, true, null);
            }

        }

        void removeDiscontinuedChallenges(List<string> discontinued)
        {
             foreach(string dChallenge in discontinued)
            {
                UIView.Animate(duration: 0.4f, delay: 0, options: UIViewAnimationOptions.CurveEaseOut, animation: () =>
                {
                    challengePads[dChallenge].Alpha = 0;
                    challengePads[dChallenge].Hidden = true;
                },

                completion: () =>
                {
                    stackView.RemoveArrangedSubview(challengePads[dChallenge]);
                    challengePads.Remove(dChallenge);
                    Filewrite.RemoveChallenge(dChallenge);
                });
            }
        }

        void Tap(UITapGestureRecognizer tap1)
        {
            System.Diagnostics.Debug.WriteLine(tap1.View.Tag);

            if(tap1.View.Tag == -1)
            {
                TipDaily f = this.Storyboard.InstantiateViewController("TipDaily") as TipDaily;
                f.thisTip = tip;
                f.imageIndex = tipImage;
                f.controller = this.NavigationController;
                NavigationController.PresentViewController(f, true, null);
            }
        }

        void challengeTap(challengeTapRecognizer tap1)
        {
            System.Diagnostics.Debug.WriteLine(tap1.ChallengeID);
        }

        public void RemoveChallenge(string id)
        {
            challengePads[id].RemoveFromSuperview();
            challengePads.Remove(id);
            challengeSecondary_Label.Remove(id);
        }

        public void UpdateChallenge(string id, int daysLeft)
        {
            System.Diagnostics.Debug.WriteLine("ddd");
            if(daysLeft < 3)
            {
                 challengeSecondary_Label[id].Text = daysLeft.ToString() + NSBundle.MainBundle.GetLocalizedString("DAYS TO GO !");
            }
            else
            {
                challengeSecondary_Label[id].Text = NSBundle.MainBundle.GetLocalizedString("COMPLETE FOR TODAY");
            }
        }

        public void AddShadow(UIView view)
        {
            view.Layer.ShadowColor = UIColor.Black.CGColor;
            view.Layer.ShadowOpacity = 0.12f;
            view.Layer.ShadowRadius = 6f;
            view.Layer.ShadowOffset = new CGSize(0,4);
            view.Layer.ShouldRasterize = true;
            view.Layer.RasterizationScale = UIScreen.MainScreen.Scale;
        }

        public class challengeTapRecognizer : UITapGestureRecognizer
        {
            public string ChallengeID;
            public UIView view;
            UIColor originalColor;
            HubDaily hub;
            Challenges.Challenge challenge;

            public challengeTapRecognizer(UIView Iview, HubDaily hubDaily, Challenges.Challenge challengL)
            {
                view = Iview;
                originalColor = Iview.BackgroundColor;
                hub = hubDaily;
                challenge = challengL;
            }

            public override void TouchesBegan(NSSet touches, UIEvent evt)
            {
                base.TouchesBegan(touches, evt);
                view.Layer.RemoveAllAnimations();
                view.BackgroundColor = UIColor.Gray;
            }

            public override void TouchesEnded(NSSet touches, UIEvent evt)
            {
                base.TouchesEnded(touches, evt);
                System.Diagnostics.Debug.WriteLine(ChallengeID);

                UIView.Animate(
                duration: 0.4f,
                delay: 0,
                options: UIViewAnimationOptions.CurveEaseIn,
                animation: () => {
                    view.BackgroundColor = originalColor;
                },
                completion: () => {
                    view.BackgroundColor = originalColor;
                }
                );

                DailyChallenge Cpage = hub.Storyboard.InstantiateViewController("DailyChallenge") as DailyChallenge;
                hub.NavigationController.PushViewController(Cpage, true);
                Cpage.challenge = challenge;
                Cpage.hub = hub;
                //Cpage.day = viewController;
            }

            public override void TouchesCancelled(NSSet touches, UIEvent evt)
            {
                base.TouchesCancelled(touches, evt);

                UIView.Animate(
                duration: 0.4f,
                delay: 0,
                options: UIViewAnimationOptions.CurveEaseIn,
                animation: () => {
                    view.BackgroundColor = originalColor;
                },
                completion: () => {
                    view.BackgroundColor = originalColor;
                }
                );
            }

            public override void Reset()
            {
                base.Reset();

                UIView.Animate(
                duration: 0.4f,
                delay: 0,
                options: UIViewAnimationOptions.CurveEaseIn,
                animation: () => {
                    view.BackgroundColor = originalColor;
                },
                completion: () => {
                    view.BackgroundColor = originalColor;
                }
                );
            }

        }
    }
}
