// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint
{
	public partial class JustTableView : UITableView
	{
		public JustTableView (IntPtr handle) : base (handle)
		{
		}

    }
}
