// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Footprint.Base.lproj
{
	public partial class TipCell : UITableViewCell
	{
		public TipCell (IntPtr handle) : base (handle)
		{

		}

        public void UpdateCell(TipLibrary.Tip tip, int imageIndex)
        {
            Label.Text = tip.TipName;
            Label.AdjustsFontSizeToFitWidth = true;
            int condition = tip.ConditionIndex;

            string iconPath = "Image/Challenge/";

            if (condition == 0)
            {
                iconPath += "FoodSource.png";
            }
            else if (condition == 1)
            {
                iconPath += "FoodPrice.png";
            }
            else if (condition == 2)
            {
                iconPath += "FoodWaste.png";
            }
            else if (condition == 3)
            {
                iconPath += "DailyTransport.png";
            }
            else if (condition == 4)
            {
                iconPath += "OccasionalTransport.png";
            }
            else if (condition == 5)
            {
                iconPath += "PaperUsage.png";
            }
            else if (condition == 6)
            {
                iconPath += "PlasticUsage.png";
            }
            else if (condition == 7)
            {
                iconPath += "GarbageManagement.png";
            }
            else if (condition == 8)
            {
                iconPath += "EnergyConsumption.png";
            }
            else if (condition == 9)
            {
                iconPath += "Enviroment.png";
            }
            Icon.Image = UIImage.FromFile(iconPath);

            var randomG = new System.Random();
            Background.Image = UIImage.FromFile("Image/ChallengeTopic/" + condition.ToString() + "/" + imageIndex.ToString() + ".jpg");
        }
	}
}
